### ISSUE TITLE
Panic: Interface conversion: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by rennu** [greenpau/caddy-auth-jwt#50]
**Issue**

I'm trying to authentication by using at+jwt token but caddy panics (see stack below). Is this even supported (am I doing it wrong?)?

**Configuration**

```
{
  http_port 8080
  https_port 8443
  debug
}

localhost:8443 {
  route /secret* {
    jwt {
      primary yes
      option validate_bearer_header
      validate allow_all
      allow audience account.api
      trusted_tokens {
        public_key {
          token_name jwt_access_token
          token_rsa_file aV2gt-6_EDGe3nKiSTyPtQ ./idp_public.pem
        }
      }
      disable auth_redirect
    }
    respond * "secret" 200
  }

  route /public* {
    respond * "public" 200
  }

  route {
    redir https://{hostport}/auth 302
  }
}
```

**Version Information**

```
$ ./caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.4
http.handlers.authentication v2.3.0```
```

**Log output**

```
2021/02/11 14:57:47.638 ERROR   http.handlers.authentication    auth provider returned error    {"provider": "jwt", "error": "[crypto/rsa: verification error]"}
2021/02/11 14:57:47.673 DEBUG   http.stdlib     http2: panic serving 127.0.0.1:56895: interface conversion: interface {} is []interface {}, not string
goroutine 89 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0000b4798, 0xc000c77f8e, 0xc000246600)
        net/http/h2_bundle.go:5712 +0x16f
panic(0x15da160, 0xc000bc5920)
        runtime/panic.go:969 +0x1b9
github.com/greenpau/caddy-auth-jwt/pkg/claims.NewUserClaimsFromMap(0xc000bc5800, 0xc000c75a40, 0xc000bd2b90, 0x0)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/claims/user.go:195 +0x3f25
github.com/greenpau/caddy-auth-jwt/pkg/claims.ParseClaims(0xc000bd2b90, 0x42a, 0xc000c75a40, 0xc000bd2b90)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/claims/user.go:483 +0x47
github.com/greenpau/caddy-auth-jwt/pkg/validator.(*TokenValidator).ValidateToken(0xc00080f780, 0xc000b37687, 0x42a, 0xc00021d0b0, 0xc000b37687, 0x42a, 0x1, 0x0)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/validator/validator.go:244 +0x968
github.com/greenpau/caddy-auth-jwt/pkg/validator.(*TokenValidator).AuthorizeAuthorizationHeader(0xc00080f780, 0xc0001b3b00, 0xc00021d0b0, 0x0, 0x0, 0x0, 0x0)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/validator/validator.go:185 +0xfa
github.com/greenpau/caddy-auth-jwt/pkg/validator.(*TokenValidator).Authorize(0xc00080f780, 0xc0001b3b00, 0xc00021d0b0, 0x0, 0x0, 0x0, 0x0)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/validator/validator.go:162 +0x22c
github.com/greenpau/caddy-auth-jwt/pkg/auth.Authorizer.Authenticate(0xc00053e160, 0x5, 0x1, 0xc00053e108, 0x7, 0x1, 0x17a1bf2, 0x5, 0x1, 0x17ccfda, ...)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/pkg/auth/authorizer.go:138 +0xad
github.com/greenpau/caddy-auth-jwt.AuthMiddleware.Authenticate(0xc000962000, 0x7f14bb3d76d8, 0xc000bc57d0, 0xc0001b3b00, 0xc0008f22c8, 0xc0008f2240, 0xc000c88a18, 0x4107c5, 0xc000c88cc8, 0x0)
        github.com/greenpau/caddy-auth-jwt@v1.2.4/plugin.go:61 +0x1d8
github.com/caddyserver/caddy/v2/modules/caddyhttp/caddyauth.Authentication.ServeHTTP(0x0, 0xc00021cc60, 0xc000610cc0, 0x7f14bb3d76d8, 0xc000bc57d0, 0xc0001b3b00, 0x1a46360, 0xc000bdede0, 0xc0281ed100, 0x7f14bb3d76d8)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyauth/caddyauth.go:76 +0x11d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0006c81a0, 0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0x1a46360, 0xc000bdede0, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0xc000bdee20, 0xc0006c81a0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000bdee20, 0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0x1, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:231 +0x128
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000bdee00, 0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0xc000bded80, 0x1a46360)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0008555a0, 0x7f14bb3d76d8, 0xc000bc5710, 0xc0001b3b00, 0x1a46360, 0xc000bded80, 0xc000bdec60, 0xc000c89108)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc00000cea0, 0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0x1a46360, 0xc000bded80, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0xc000bdedc0, 0xc00000cea0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000bdedc0, 0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0x1, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:231 +0x128
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000bdeda0, 0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0x188a600, 0x1a46360)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc00052bf60, 0x7f14bb3d76d8, 0xc000bc5650, 0xc0001b3b00, 0x1a46360, 0x188a600, 0x9, 0x9)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0004946e0, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0x1a46360, 0x188a600, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0xc000bded20, 0xc0004946e0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000bded20, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0x1, 0xc000968880)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0x40da50, 0xc000bc5590)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/routes.go:231 +0x128
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000494700, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0x2, 0x0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc00096afc0, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0x1a46360, 0xc000494700, 0x59a784aa2cd0, 0x281e7af8)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/server.go:295 +0x9d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0xc0281e7af8, 0x59a784aa2cd0)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/server.go:271 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000494720, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00, 0xc00081fb00, 0xc0001b3b00)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/caddyhttp.go:55 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc00096afc0, 0x1a5efa0, 0xc0000b4798, 0xc0001b3b00)
        github.com/caddyserver/caddy/v2@v2.3.0/modules/caddyhttp/server.go:207 +0x4bd
net/http.serverHandler.ServeHTTP(0xc000ba0d20, 0x1a5efa0, 0xc0000b4798, 0xc0001b2100)
        net/http/server.go:2843 +0xa3
net/http.initALPNRequest.ServeHTTP(0x1a641e0, 0xc000d82060, 0xc0002f8000, 0xc000ba0d20, 0x1a5efa0, 0xc0000b4798, 0xc0001b2100)
        net/http/server.go:3415 +0x8d
net/http.(*http2serverConn).runHandler(0xc000246600, 0xc0000b4798, 0xc0001b2100, 0xc000bdec00)
        net/http/h2_bundle.go:5719 +0x8b
created by net/http.(*http2serverConn).processHeaders
        net/http/h2_bundle.go:5453 +0x505
```

**Comment by greenpau** [comment]
@rennu , did you review https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-public-keys ?

Next, please paste the content of `idp_public.pem`.

Did you try full path to the pem file?

> Is this even supported (am I doing it wrong?)?

It is supported per the doc above. I suspect your `.pem` file does not parse well.

**Comment by rennu** [comment]
Hi,

Yes, I followed the instructions except for the key creation part, since those are supplied by the existing system. I've also tried using a full path to the file but it didn't change anything.

Here's the public key:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0qSfYvanMfmwfD75kMWR
dAr+9n3/WQ9GGjzb2q/13diJmpNxtVAxrL8e31kstVq6vtHe/R0nKOB75/9ehCGI
UwQWEJXoCEYZnxo3HPteOaFDKOd1/V89FfVjKb63IM3qI43Ctj/F+6Gl17boDnaL
+JItGCdNOp30CeEtZM5IX5HeoQr7+ASlPMz57QhOeGluK/UnGBliPTi/N+S3F1h9
KUZApn0fXPi/EfPqQIz3EDSjJDkCaGMQqjbV4F1Gbb+TZ8GieiJaQx9gQv4fdVhS
P4r2ztHIa8KYz3FJQWMRQhH/CLs37c+W9IyF4rM3dVnw8GU8JNvbiqBMuLTWTNZc
8wIDAQAB
-----END PUBLIC KEY-----
```

I assume the plugin tries to verify the token after reading exp and making sure that the token isn't expired? I tried to replicate the problem before replying but with expired token the error didn't manifest.

**Comment by greenpau** [comment]
> Yes, I followed the instructions except for the key creation part, since those are supplied by the existing system. I've also tried using a full path to the file but it didn't change anything.

@rennu , the plugin supports the following:

https://github.com/greenpau/caddy-auth-jwt/blob/2363a4362fa17513fb62e30b3b820227427f092d/pkg/config/methods.go#L19-L24

> [crypto/rsa: verification error]

This error might mean that something is wrong with that pem file.

On its face I can unpack it.

```
$ openssl rsa -noout -text -inform PEM -in  public.pem -pubin
RSA Public-Key: (2048 bit)
Modulus:
    00:d2:a4:9f:62:f6:a7:31:f9:b0:7c:3e:f9:90:c5:
    91:74:0a:fe:f6:7d:ff:59:0f:46:1a:3c:db:da:af:
    f5:dd:d8:89:9a:93:71:b5:50:31:ac:bf:1e:df:59:
    2c:b5:5a:ba:be:d1:de:fd:1d:27:28:e0:7b:e7:ff:
    5e:84:21:88:53:04:16:10:95:e8:08:46:19:9f:1a:
    37:1c:fb:5e:39:a1:43:28:e7:75:fd:5f:3d:15:f5:
    63:29:be:b7:20:cd:ea:23:8d:c2:b6:3f:c5:fb:a1:
    a5:d7:b6:e8:0e:76:8b:f8:92:2d:18:27:4d:3a:9d:
    f4:09:e1:2d:64:ce:48:5f:91:de:a1:0a:fb:f8:04:
    a5:3c:cc:f9:ed:08:4e:78:69:6e:2b:f5:27:18:19:
    62:3d:38:bf:37:e4:b7:17:58:7d:29:46:40:a6:7d:
    1f:5c:f8:bf:11:f3:ea:40:8c:f7:10:34:a3:24:39:
    02:68:63:10:aa:36:d5:e0:5d:46:6d:bf:93:67:c1:
    a2:7a:22:5a:43:1f:60:42:fe:1f:75:58:52:3f:8a:
    f6:ce:d1:c8:6b:c2:98:cf:71:49:41:63:11:42:11:
    ff:08:bb:37:ed:cf:96:f4:8c:85:e2:b3:37:75:59:
    f0:f0:65:3c:24:db:db:8a:a0:4c:b8:b4:d6:4c:d6:
    5c:f3
Exponent: 65537 (0x10001)
```

Next step, please paste here the token you pass to the plugin to validate. That's necessary to check that the kid the token carries matches the configuration.

**Comment by greenpau** [comment]
@rennu , last release adding new changes. Could you please try changing to `v1.2.3`? I want to see whether you experience the same issue.

Please use https://jwt.io/ to convert your token to human readable form. I just need "header" and "payload".

**Comment by greenpau** [comment]
> I assume the plugin tries to verify the token after reading exp

@rennu , when you get the panic? during startup or when token validation happens?

**Comment by rennu** [comment]
Hi,

1.2.3 panics too (the stack is pretty much 1:1). I had to modify Caddyfile a bit because some of the features weren't available in 1.2.3 (see below).

The panic happends at validation.

```
{
  http_port 8080
  https_port 8443
  debug
}

localhost:8443 {
  route /secret* {
    jwt {
      primary yes
      option validate_bearer_header
      allow roles admin
      trusted_tokens {
        public_key {
          token_name jwt_access_token
          token_rsa_file aV2gt-6_EDGe3nKiSTyPtQ ./idp_public.pem
        }
      }
    }
    respond * "secret" 200
  }

  route /public* {
    respond * "public" 200
  }

  route {
    redir https://{hostport}/auth 302
  }
}
```

Token (using jwt.io)

**header**:
```
{
  "alg": "RS256",
  "kid": "aV2gt-6_EDGe3nKiSTyPtQ",
  "typ": "at+jwt"
}
```

**payload**
```
{
  "nbf": 1613146378,
  "exp": 1613149978,
  "iss": "https://[redacted]",
  "aud": "account.api",
  "client_id": "account",
  "sub": "e28c6521-f877-4138-a540-a8981f7ee095",
  "auth_time": 1613142427,
  "idp": "local",
  "name": [
    "email@example.com",
    "My Name"
  ],
  "email": "email@example.com",
  "scope": [
    "openid",
    "profile",
    "account"
  ],
  "amr": [
    "pwd"
  ]
}
```

**Comment by greenpau** [comment]
@rennu , found the issue. Will explain tomorrow. Do you have control over the issued token, specifically “name” field.

**Comment by greenpau** [comment]
@rennu , the name field in the token is expected to be a string. In your token, it is an array of strings, i.e. your email and name. I can fix this problem by returning a concatenated string from an array, or you can fix the name field to only include a string.

with that said, I need to improve the error handling in that function.

**Comment by rennu** [comment]
@greenpau Oh, I see. No idea why name field would include email address anyways since it has it's own field. I'll ask if it's possible to change it to an actual name string.

**Comment by greenpau** [comment]
@rennu , I will put a patch to allow you to use your current token "as is". Will happen today. Will keep you posted.

**Comment by rennu** [comment]
@greenpau Wow, thank you!

**Comment by greenpau** [comment]
@rennu , test with the following version `caddy-auth-jwt v1.2.5` and it should work. Please reply with results, errors, etc.

**Comment by rennu** [comment]
@greenpau Hi, it works! Thank you!
